---
name: Geo-Postcodes-DK
version: 0.31
author:
abstract: Danish postcodes with associated information
license: perl
requires:
  Geo::Postcodes: 0.31
  perl: 5.6.1
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Geo::Postcodes::DK:
    file: lib/Geo/Postcodes/DK.pm
    version: 0.31
resources:
  license: http://dev.perl.org/licenses/
