# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Postcodes-DK
version:      0.30
version_from: DK.pm
installdirs:  site
requires:
    Geo::Postcodes:                0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
