--- #YAML:1.0
name:               Geo-Postcodes-DK
version:            0.32
abstract:           Danish postcodes with associated information
author:
    - Arne Sommer <perl@bbop.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Geo::Postcodes:  0.31
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
